services:
  - type: web
    name: elfie-labs-backend-api
    runtime: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: QWEN_API_KEY
        sync: false
